import type { Metadata } from 'next';
import { Geist, Geist_Mono, Onest } from 'next/font/google';
import './globals.css';

const onest = Onest({
  subsets: ['latin'],
  variable: '--font-onest',
});

export const metadata: Metadata = {
  title: 'HollywoodAI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${onest.className} antialiased`}>
        {children}
        <script src='https://kit.fontawesome.com/e55bf0d525.js' crossOrigin='anonymous' />
      </body>
    </html>
  );
}
